// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package sqlc

import (
	"context"
)

const createParticipant = `-- name: CreateParticipant :exec
INSERT INTO participant(track, email) VALUES ($1, $2)
`

type CreateParticipantParams struct {
	Track string
	Email string
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) error {
	_, err := q.db.ExecContext(ctx, createParticipant, arg.Track, arg.Email)
	return err
}
